---
# Plan
---

In [1]:
# Import packages
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import json
import os

In [2]:
# Defining imports paths
subject_id = 7
tms_output_path = os.path.join("tms_output",f"covid_vaccine_new-subject{subject_id}")

In [3]:
# Loading clusters data into python
node_info = pd.read_csv(os.path.join(tms_output_path, "node_info.csv"), index_col=0).reset_index()
clusters = pd.read_csv(os.path.join(tms_output_path, "clusters.csv"), index_col=0)

In [4]:
node_info

        node    size         Q
0          0  246808  0.338846
1          1  154625  0.266728
2          2   94906  0.184842
3          3   61974  0.180891
4          4   44209  0.065058
...      ...     ...       ...
99132  99132       4       NaN
99133  99133       6  0.015076
99134  99134       3       NaN
99135  99135       3       NaN
99136  99136       3       NaN

[99137 rows x 3 columns]

In [5]:
clusters

,cluster,path
cell,,
LYLQMNSLRAEDTAVYYCAR,25523,25523/25522/25521/25509/25508/25507/25506/2550...
YLQMNSLRAEDTAVYYCARD,25473,25473/25472/25471/25469/25468/25467/25455/2542...
sLKLSsVTAADTAVYYCARG,29669,29669/29668/29667/29661/29660/29648/29647/2951...
NTLYLQMNSLRAEDTAVYYC,25513,25513/25512/25511/25510/25509/25508/25507/2550...
TLYLQMNSLRAEDTAVYYCA,25516,25516/25515/25511/25510/25509/25508/25507/2550...
...,...,...
LRSLRsDDTAVYYCARVNIW,13303,13303/13302/13300/13299/13298/13297/13296/1329...
ELRSLRsDDTAVYYCARVNI,13305,13305/13299/13298/13297/13296/13295/12467/1246...
CGSQWLPDYWGQGTLxTVxs,38845,38845/38844/38843/38825/38721/38720/38719/3871...
YCGSQWLPDYWGQGTLxTVx,38845,38845/38844/38843/38825/38721/38720/38719/3871...
YYCARVNIWDNWSVRsRRxY,16553,16553/16551/16550/16548/16542/16541/16540/1653...

In [1]:
"test".split(",")

['test']